name:  PR open
on:
  pull_request:
    branches: [ "master" ]
    paths:
      - .github/workflows/*.yml
      - ./**
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
jobs:
  prequel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v1
        id: matrixer
        with:
          script: |
            let pr= github
            return pr
      - name: Get result
        run: echo "${{steps.matrixer.outputs.result}}"
  parser1:
    #if: github.payload.pull_request.title.split('-')[0] == 'deploy'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v1
        id: matrix
        with:
          script: |
            let head =  context.payload.pull_request.title.split('-');
            let matrix = { 
              environment: ["dev"],
              location:    ["westus2", "eastus2"]
            };
            echo matrix.location.includes("eastus2")
            if( head != null && head[0] == 'dev' )
            {
              matrix = {
                environment: ["dev"],
                location:    [head[1]]
              }
            }
            core.setOutput('matrix',matrix);

  Job11:
    needs: parser1
    strategy:
      matrix: ${{ fromJson(needs.parser1.outputs.matrix) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
     - name: Output curren env-locaiton
       run: |
        echo env=${{ matrix.environment }}
        echo loc=${{ matrix.location }}
  Job2:
    needs: parser1
    runs-on: ubuntu-latest
    steps:
     - name: Output curren env-locaiton
       run: |
        echo env="jai"   